---
language: cpp
dist: bionic
env:
  CGAL_VERSION: 4.13.1

addons:
  apt:
    packages:
      - libcgal-dev
      - libboost-dev
      - libboost-system-dev
      - libboost-thread-dev

script:
  - cd ./XFREE
  - cmake .
  - make
  - cd ../CTR
  - cmake .
  - make
